### ISSUE TITLE
cant build on centos 5.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#256]
```
What steps will reproduce the problem?

python setup.py build

What is the expected output? What do you see instead?

[root@ip-10-17-129-112 pyrit]# python setup.py build
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe -Wall 
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector 
--param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fPIC 
-I/usr/include/python2.4 -c cpyrit/_cpyrit_cpu.c -o 
build/temp.linux-x86_64-2.4/cpyrit/_cpyrit_cpu.o -Wall -fno-strict-aliasing 
-DVERSION="0.4.0-dev (svn r288)"
cpyrit/_cpyrit_cpu.c:88: error: expected specifier-qualifier-list before 
‘Py_ssize_t’
cpyrit/_cpyrit_cpu.c: In function ‘EAPOLCracker_solve’:
cpyrit/_cpyrit_cpu.c:976: error: ‘Py_ssize_t’ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c:976: error: (Each undeclared identifier is reported only 
once
cpyrit/_cpyrit_cpu.c:976: error: for each function it appears in.)
cpyrit/_cpyrit_cpu.c:976: error: expected ‘;’ before ‘buffersize’
cpyrit/_cpyrit_cpu.c:998: error: ‘buffersize’ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c: At top level:
cpyrit/_cpyrit_cpu.c:1087: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ 
or ‘__attribute__’ before ‘CowpattyResult_bf_getreadbuffer’
cpyrit/_cpyrit_cpu.c:1099: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ 
or ‘__attribute__’ before ‘CowpattyResult_bf_getsegcount’
cpyrit/_cpyrit_cpu.c:1107: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ 
or ‘__attribute__’ before ‘CowpattyResult_sq_length’
cpyrit/_cpyrit_cpu.c:1113: error: expected declaration specifiers or ‘...’ 
before ‘Py_ssize_t’
cpyrit/_cpyrit_cpu.c: In function ‘CowpattyResult_sq_item’:
cpyrit/_cpyrit_cpu.c:1118: error: ‘idx’ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c:1118: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c:1126: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c:1135: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c:1136: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c: In function ‘CowpattyResult_iternext’:
cpyrit/_cpyrit_cpu.c:1155: error: ‘CowpattyResult’ has no member named 
‘current_idx’
cpyrit/_cpyrit_cpu.c:1155: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c:1167: error: ‘CowpattyResult’ has no member named 
‘current_idx’
cpyrit/_cpyrit_cpu.c:1170: error: ‘CowpattyResult’ has no member named 
‘current_idx’
cpyrit/_cpyrit_cpu.c: In function ‘CowpattyFile_unpackcowpentries’:
cpyrit/_cpyrit_cpu.c:1328: error: ‘CowpattyResult’ has no member named 
‘buffersize’
cpyrit/_cpyrit_cpu.c:1329: error: ‘CowpattyResult’ has no member named 
‘current_idx’
cpyrit/_cpyrit_cpu.c:1330: error: ‘CowpattyResult’ has no member named 
‘itemcount’
cpyrit/_cpyrit_cpu.c: In function ‘PcapDevice_send’:
cpyrit/_cpyrit_cpu.c:1595: error: ‘Py_ssize_t’ undeclared (first use in 
this function)
cpyrit/_cpyrit_cpu.c:1595: error: expected ‘;’ before ‘pckt_size’
cpyrit/_cpyrit_cpu.c:1614: error: ‘pckt_size’ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c: At top level:
cpyrit/_cpyrit_cpu.c:1839: error: ‘readbufferproc’ undeclared here (not in 
a function)
cpyrit/_cpyrit_cpu.c:1839: error: expected ‘}’ before 
‘CowpattyResult_bf_getreadbuffer’
cpyrit/_cpyrit_cpu.c:1846: error: ‘lenfunc’ undeclared here (not in a 
function)
cpyrit/_cpyrit_cpu.c:1846: error: expected ‘}’ before 
‘CowpattyResult_sq_length’
error: command 'gcc' failed with exit status 1


What version of the product are you using? On what operating system?

pyrit svn
centos 5.5
gcc 4.1.2

Please provide any additional information below.

```

Original issue reported on code.google.com by `nucho...@gmail.com` on 3 Feb 2011 at 12:27
