### ISSUE TITLE
_cpyrit_cuda.c:39: fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#294]
```
I'm trying to compile on Ubuntu 10.1 and get the following error.

/cpyrit-cuda-0.4.0$ sudo python setup.py build
svn: '.' is not a working copy
running build
running build_ext
Skipping rebuild of Nvidia CUDA kernel ...
Building modules...
building 'cpyrit._cpyrit_cuda' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall 
-Wstrict-prototypes -fPIC -I/usr/local/cuda/include -I/usr/include/python2.6 -c 
_cpyrit_cuda.c -o build/temp.linux-x86_64-2.6/_cpyrit_cuda.o -Wall 
-fno-strict-aliasing -DVERSION="0.4.0"
_cpyrit_cuda.c:39: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

any help would be appreciated 
```

Original issue reported on code.google.com by `spliff...@googlemail.com` on 7 Apr 2011 at 12:13
