### ISSUE TITLE
Unable to build on centos 5.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#254]
```
What steps will reproduce the problem?
1. Unable to build on centos 5.5
2.
3.

What is the expected output? What do you see instead?

[root@fuck pyrit]# python setup.py build
running build
running build_py
running build_ext
building 'cpyrit._cpyrit_cpu' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -O2 -g -pipe -Wall 
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-pro                     tector 
--param=ssp-buffer-size=4 -m32 -march=i386 -mtune=generic 
-fasynchronous-unwind-tables -D_GNU_SOURCE -f                     PIC -fPIC 
-I/usr/include/python2.4 -c cpyrit/_cpyrit_cpu.c -o 
build/temp.linux-i686-2.4/cpyrit/_cpyrit_cpu.o -                     Wall 
-fno-strict-aliasing -DVERSION="0.4.0-dev (svn r288)"
cpyrit/_cpyrit_cpu.c:88: error: expected specifier-qualifier-list before 
âPy_ssize_tâ
cpyrit/_cpyrit_cpu.c: In function âEAPOLCracker_solveâ:
cpyrit/_cpyrit_cpu.c:976: error: âPy_ssize_tâ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c:976: error: (Each undeclared identifier is reported only 
once
cpyrit/_cpyrit_cpu.c:976: error: for each function it appears in.)
cpyrit/_cpyrit_cpu.c:976: error: expected â;â before âbuffersizeâ
cpyrit/_cpyrit_cpu.c:998: error: âbuffersizeâ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c: At top level:
cpyrit/_cpyrit_cpu.c:1087: error: expected â=â, â,â, â;â, âasmâ or 
â__attribute__â before âCowpattyResult_bf_g                     
etreadbufferâ
cpyrit/_cpyrit_cpu.c:1099: error: expected â=â, â,â, â;â, âasmâ or 
â__attribute__â before âCowpattyResult_bf_g                     etsegcountâ
cpyrit/_cpyrit_cpu.c:1107: error: expected â=â, â,â, â;â, âasmâ or 
â__attribute__â before âCowpattyResult_sq_l                     engthâ
cpyrit/_cpyrit_cpu.c:1113: error: expected declaration specifiers or â...â 
before âPy_ssize_tâ
cpyrit/_cpyrit_cpu.c: In function âCowpattyResult_sq_itemâ:
cpyrit/_cpyrit_cpu.c:1118: error: âidxâ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c:1118: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c:1126: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c:1135: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c:1136: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c: In function âCowpattyResult_iternextâ:
cpyrit/_cpyrit_cpu.c:1155: error: âCowpattyResultâ has no member named 
âcurrent_idxâ
cpyrit/_cpyrit_cpu.c:1155: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c:1167: error: âCowpattyResultâ has no member named 
âcurrent_idxâ
cpyrit/_cpyrit_cpu.c:1170: error: âCowpattyResultâ has no member named 
âcurrent_idxâ
cpyrit/_cpyrit_cpu.c: In function âCowpattyFile_unpackcowpentriesâ:
cpyrit/_cpyrit_cpu.c:1328: error: âCowpattyResultâ has no member named 
âbuffersizeâ
cpyrit/_cpyrit_cpu.c:1329: error: âCowpattyResultâ has no member named 
âcurrent_idxâ
cpyrit/_cpyrit_cpu.c:1330: error: âCowpattyResultâ has no member named 
âitemcountâ
cpyrit/_cpyrit_cpu.c: In function âPcapDevice_sendâ:
cpyrit/_cpyrit_cpu.c:1595: error: âPy_ssize_tâ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c:1595: error: expected â;â before âpckt_sizeâ
cpyrit/_cpyrit_cpu.c:1614: error: âpckt_sizeâ undeclared (first use in this 
function)
cpyrit/_cpyrit_cpu.c: At top level:
cpyrit/_cpyrit_cpu.c:1839: error: âreadbufferprocâ undeclared here (not in a 
function)
cpyrit/_cpyrit_cpu.c:1839: error: expected â}â before 
âCowpattyResult_bf_getreadbufferâ
cpyrit/_cpyrit_cpu.c:1846: error: âlenfuncâ undeclared here (not in a 
function)
cpyrit/_cpyrit_cpu.c:1846: error: expected â}â before 
âCowpattyResult_sq_lengthâ
error: command 'gcc' failed with exit status 1


What version of the product are you using? On what operating system?
Pyrit 0.4.0

Please provide any additional information below.

gcc 2.4

Linux fuck.evils  2.6.18-194.32.1.el5 #1 SMP Wed Jan 5 17:53:09 EST 2011 i686 
i686 i386 GNU/Linux


```

Original issue reported on code.google.com by `thefixe...@gmail.com` on 2 Feb 2011 at 10:19
