### ISSUE TITLE
How to Install Pyrit Cuda + Toolkit 8 + Nvidia GTX 1070  in Kali Linux 2017.1

### ISSUE THREAD

**Issue by reproteq** [JPaulMora/Pyrit#528]
Install Kali Linux 2017.1 + Nvidia GTX-1070 drivers + Toolkit + Gpu Pyrit Cuda Cores
	
https://github.com/JPaulMora/Pyrit	                                               descargar y dar permisos
	
https://developer.nvidia.com/cuda-downloads	
	
chmod +x cuda_8.0.61_375.26_linux.run	
	
http://www.nvidia.com/download/index.aspx?lang=es	
	
chmod +x NVIDIA-Linux-x86_64-375.66.run	
	
	
	
leafpad /etc/apt/sources.list	                                                             editar fuentes
deb http://http.kali.org/kali kali-rolling main non-free contrib	
deb-src http://http.kali.org/kali kali-rolling main non-free contrib	
	
	
	
apt-get update	                                                                                   actualizar distro e instalar headers
apt-get dist-upgrade	
apt-get install -y linux-headers-$(uname -r)	
	
	
	
sed 's/quiet/quiet nouveau.modeset=0/g' -i /etc/default/grub	
update-grub	
reboot	
	
	
	
ctrl+alt+f3	                                                                                    modo consola sin entorno grafico
login root	
	
./NVIDIA-Linux-x86_64-375.66.run	                                              instalar driver nvidia
update-grub	
reboot	
	
	
export PERL5LIB=.	instalar cuda toolkit
./cuda_8.0.61_375.26_linux.run --override	
	
ldconfig -v 2>/dev/null | grep -v ^$'\t'	                                       muestra paths
leafpad /etc/ld.so.conf	                                                               editar config paths
/usr/local/cuda-8.0/lib64                                                           	incluir esta linea en ld.so.conf
	
	
apt-get install python2.7-dev libssl-dev zlib1g-dev libpcap-dev	    instala libs
	
git clone https://github.com/JPaulMora/Pyrit.git	descargar
	
	
python setup.py build	
python setup.py install	
	
Pyrit/modules/cpyrit_cuda/setup.py	editar el setup.py
leafpad setup.py	

                                                                                                                  buscar y reemplazar
                        
nvcc_cmd = NVCC + bit_flag + ' -Xcompiler "-fPIC" --ptx' \
                                         ' ./_cpyrit_cudakernel.cu'                                                                        
	
                                                                                                                    quedaria asi
nvcc_cmd = NVCC + bit_flag + ' -ccbin clang' \	
                                          ' ./_cpyrit_cudakernel.cu'
	
	
	
leafpad /root/.pyrit/config	                                                                            editar 
use_CUDA = true	
	
pyrit list_cores	cores cpu gpu
		
pyrit benchmark

Computed 118727.81 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 570.0 PMKs/s (RTT 2.9)
#2: 'CPU-Core (SSE2/AES)': 563.3 PMKs/s (RTT 3.0)
#3: 'CPU-Core (SSE2/AES)': 575.7 PMKs/s (RTT 3.0)
#4: 'CPU-Core (SSE2/AES)': 578.7 PMKs/s (RTT 3.0)
#5: 'CPU-Core (SSE2/AES)': 567.0 PMKs/s (RTT 3.0)
#6: 'CPU-Core (SSE2/AES)': 535.9 PMKs/s (RTT 2.9)
#7: 'CPU-Core (SSE2/AES)': 551.7 PMKs/s (RTT 2.9)
#8: 'CPU-Core (SSE2/AES)': 560.9 PMKs/s (RTT 3.1)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1070'': 127866.4 PMKs/s (RTT 1.0)

**Comment by JPaulMora** [comment]
Thanks, I'll edit `nvcc_cmd = NVCC + bit_flag + ' -ccbin clang' ' ./_cpyrit_cudakernel.cu'` directly in the source

**Comment by reproteq** [comment]
Thanks and sorry this is the correct code else errors.

            nvcc_cmd = NVCC + bit_flag + ' -ccbin clang'\
                                         ' -Xcompiler "-fPIC" --ptx' \
                                         ' ./_cpyrit_cudakernel.cu'

**Comment by JPaulMora** [comment]
ok

**Comment by emrysrind** [comment]
all works well but I cannot install toolkit its been a while that I am trying to install it
at every ends it shows same missing library message
which wasnt there before 8.0 version
sadly not even cuda 7.5 is working anymore
gives the same error
any help/suggestions ?



Description

This package includes over 100+ CUDA examples that demonstrate
various CUDA programming principles, and efficient CUDA
implementation of algorithms in specific application domains.
The NVIDIA CUDA Samples License Agreement is available in
Chapter 2.
Do you accept the previously read EULA?
accept/decline/quit: accept

You are attempting to install on an unsupported configuration. Do you wish to continue?
(y)es/(n)o [ default is no ]: y

Install NVIDIA Accelerated Graphics Driver for Linux-x86_64 375.26?
(y)es/(n)o/(q)uit: n

Install the CUDA 8.0 Toolkit?
(y)es/(n)o/(q)uit: y

Enter Toolkit Location
 [ default is /usr/local/cuda-8.0 ]: 

Do you want to install a symbolic link at /usr/local/cuda?
(y)es/(n)o/(q)uit: y

Install the CUDA 8.0 Samples?
(y)es/(n)o/(q)uit: y

Enter CUDA Samples Location
 [ default is /root ]: 

Installing the CUDA Toolkit in /usr/local/cuda-8.0 ...
Missing recommended library: libXi.so
Missing recommended library: libXmu.so

Warning: cannot find Toolkit in /usr/local/cuda-8.0. Use --toolkitpath to specify the toolkit location.
Installing the CUDA Samples in /root ...
sh: 1: /usr/local/cuda-8.0/bin/cuda-install-samples-8.0.sh: not found
chown: cannot access '/root/NVIDIA_CUDA-8.0_Samples': No such file or directory

===========
= Summary =
===========

Driver:   Not Selected
Toolkit:  Installation Failed
Samples:  Installation Failed


Logfile is /tmp/cuda_install_2039.log

**Comment by JPaulMora** [comment]
Weird, this seems like a bug with the toolkit installer.. why don't you try installing from the default repositories for your distro?

**Comment by emrysrind** [comment]
you mean apt-get install cudatoolkit ?

**Comment by JPaulMora** [comment]
yes

**Comment by reproteq** [comment]
download cuda 8  from nvidia develorpers
type:
export PERL5LIB=.	 
and install cudatoolkit type:                                                                 
./cuda_8.0.61_375.26_linux.run --override	
and acept everythings but not driver because driver nvidia i install previusly

**Comment by reproteq** [comment]
pyrit cudas is working in kali linux 2017.1 and last driver nvidia and toolkit 8.xx
i tested and work 100% friend
gpu compute aprox 130.000 pmks

**Comment by h3xcmd** [comment]
I am stuck.. and _float128 is above **mind blown** head... What am I missing? 

`usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h(101): error: identifier "__float128" is undefined

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h(102): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00005498_00000000-7__cpyrit_cudakernel.cpp1.ii".
`
in the file std_abs.h line 101 and 102.  
```
#if !defined(__STRICT_ANSI__) && defined(_GLIBCXX_USE_FLOAT128)
  inline _GLIBCXX_CONSTEXPR
  __float128
  abs(__float128 __x)
  { return __x < 0 ? -__x : __x; }
#endif

```

**Comment by HaxorGaruda** [comment]
nice tutorial @h3xcmd  ... thanks so much ... 
i just follow edit the std_abs.h and setup.py on cpyrit_cuda, everythings work fine ... but i don't follow to install legacy driver ... because official distro has different way : 
https://www.kali.org/news/cloud-cracking-with-cuda-gpu/
and if i  follow your step, it will be remove arch 32 on my kali linux 64 bit ... (ex : wine32)
thanks...

**Comment by h3xcmd** [comment]
Your Welcome @HaxorGaruda 
As much as I struggled with this for a whole year on my Optimus Dell Latitude (intel+nvidia) I really wish it was as simple as 

`apt-get install -y ocl-icd-libopencl1 nvidia-driver nvidia-cuda-toolkit  `

I too thought it was a bit overkill to include nvidia legacy and the long list of installs for the nvidia driver step and you are right about something, breaking the system if you install or have 32bit arch is eminent with nvidia 64. After enabling 386 arch `dpkg --add-architecture i386 && apt-get update   ` it runs through the rolling repositories it tries to install 32bit nvidia drivers and that just messes up the mods with xorg.conf stopping gdm3 from loading. Through my trial and error with an Optimus system I have learned to just not use 32bit arch. 

If you have discrete Nvidia hardware, I do not see a problem using the simplified install from the Kali Docs and yes your method would work. But in an Optimus laptop something is missing where it needs to switch from intel to nvidia and to be able to disable that switching ability to benchmark pyrit_cuda is what I came up with.  

After figuring out what FLOAT_128 meant,  the std_abs.h file was the most important step out of all of this besides figuring out the cocktail of installs to do.

**Comment by Dukeasas** [comment]
Hey guys, not sure what is going on here...can someone helpme plz??

root@Duke:~/Desktop/Pyrit/modules/cpyrit_cuda# sudo python setup.py install
running install
running build
running build_ext
Compiling CUDA module using nvcc 9.0, V9.0.176...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h(101): error: identifier "__float128" is undefined

/usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h(102): error: identifier "__float128" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00002c44_00000000-6__cpyrit_cudakernel.cpp1.ii".
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1
root@Duke:~/Desktop/Pyrit/modules/cpyrit_cuda# python -c 'from cpyrit import _cpyrit_cuda'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name _cpyrit_cuda

**Comment by c3ph3u5qwerty** [comment]
hi, i have  a problem when run "pyrit list_cores" only show me the processor cores. i have a gtx 1060 video card. are there other steps for install? thanks

**Comment by Taslack** [comment]
@c3ph3u5qwerty If you are on a laptop you need to use `optirun pyrit list_cores`, ect. ect.

**Comment by c3ph3u5qwerty** [comment]
@Taslack i have a desktop pc, i follow step by step but pyrit dont recognise the gpu core

**Comment by h3xcmd** [comment]
@c3ph3u5qwerty I am going to edit my answer even though its geared to Optimus Laptops that want to ditch the Intel display driver and go 100% with nvidia without auto switching with bumblebee where you do not need to run optirun. 
@Taslack  Optirun is for bumblebee-nvidia-driver Optimus laptops where you would want to use your default Intel display drivers and when needed to auto switch to Nvidia to accelerate your graphics. and in the past I never had any luck whatsoever with bumblebee and pyrit. You absolutely need the nvidia-drivers.   

On this last fresh install with 2017.2 updated to Kali 2017.3; installing Pyrit, I did not need to edit the FLOAT_128 integer and I did not have to install a block of librarys and nvidia stuff previously mentioned. Its all included in the `apt install nvidia-driver ocl-icd-libopencl1 nvidia-cuda-toolkit`

**Comment by Andiansyah23** [comment]
Hi i need help!!

`root@0mount:/0mount/wifi_attack/Pyrit/modules/cpyrit_cuda# python setup.py clean build install
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 93, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1
`

**Comment by Andiansyah23** [comment]
> root@0mount:/0mount/wifi_attack/Pyrit/modules/cpyrit_cuda# python setup.py clean build install
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 170, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 93, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

**Comment by kudzie567** [comment]
Also encountering the error below after _**python setup.py clean build install**_  when installing cpyrit_cuda. Here is the error:
python /opt/Pyrit-master/modules/cpyrit_cuda/setup.py clean build install
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/lib/nvidia-cuda-toolkit/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "/opt/Pyrit-master/modules/cpyrit_cuda/setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/Pyrit-master/modules/cpyrit_cuda/setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/lib/nvidia-cuda-toolkit/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

**Comment by Hackitfree** [comment]
Finally made it work on RYZEN 5 1600 with NVIDIA GTX 1060 3G...Getting 110 000 PMK/s (CPU+GPU)..
I was getting errors like all of you but since i changed ( clang to clang-3.8) in setup.py  in root@kali:/Pyrit/modules/cpyrit_cuda# everything works well.. Thank you guys for this thread !!!!

**Comment by PastiiJ** [comment]
Thank you all! Nice work!

root@KaliDesktop:/opt/Pyrit-master/modules/cpyrit_cuda# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (149966.0 PMKs/s)... / 

Computed 149965.98 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 600.7 PMKs/s (RTT 3.0)
#2: 'CPU-Core (SSE2/AES)': 608.6 PMKs/s (RTT 3.0)
#3: 'CPU-Core (SSE2/AES)': 602.4 PMKs/s (RTT 2.9)
#4: 'CPU-Core (SSE2/AES)': 625.4 PMKs/s (RTT 2.9)
#5: 'CPU-Core (SSE2/AES)': 591.3 PMKs/s (RTT 3.0)
#6: 'CPU-Core (SSE2/AES)': 604.2 PMKs/s (RTT 2.9)
#7: 'CPU-Core (SSE2/AES)': 614.4 PMKs/s (RTT 3.0)
#8: 'CPU-Core (SSE2/AES)': 604.4 PMKs/s (RTT 3.1)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1080 Ti'': 161781.1 PMKs/s (RTT 0.8)

**Comment by Hackitfree** [comment]
@ PastiiJ ..I see you have 8 threads of processor working in pyrit and you get 160 000PMK/s..Its GTX 1080 Ti -You should get more...Disable all cores but 1 in .Pyrit / config files  writing No of cpu's=1..You should get much better result...And free resources to do something else ;)..Anyway i get on my GTX 1060 128 000 PMK/s maximum speed...1 CPU core working..Tell me if it improved please :)

**Comment by PastiiJ** [comment]
Wooow thx Hackitfree !!

root@KaliDesktop:/opt/Pyrit-master/modules/cpyrit_cuda# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (224931.1 PMKs/s)... | 

Computed 224931.07 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 1341.9 PMKs/s (RTT 2.9)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1080 Ti'': 244530.3 PMKs/s (RTT 0.5)

**Comment by Hackitfree** [comment]
How to Install Pyrit Cuda + Toolkit 8 + Nvidia GTX 1060 in Kali Linux 2017.3

*Clean Install Kali 2017.3 Kernel 4.13.0-kali1-amd64 and Update

apt update && apt upgrade && apt autoremove && apt -f install && apt upgrade

apt remove pyrit

echo -e "blacklist nouveau\noptions nouveau modeset=0\nalias nouveau off" > /etc/modprobe.d/blacklist-nouveau.conf

update-initramfs -u && reboot

*Verify nouveau is disabled

lsmod | grep -i nouveau

*must be a blank return

apt install nvidia-driver ocl-icd-libopencl1 nvidia-cuda-toolkit

apt install mesa-utils nvidia-cuda-gdb nvidia-cuda-doc libssl-dev zlib1g-dev libpcap-dev libgl1-nvidia-glx python2.7-dev python-pycuda-doc python-pycuda python3-pycuda

reboot

*Pyrit prep

git clone https://github.com/JPaulMora/Pyrit.git

gedit /root/.bashrc

*Add these lines to the end of .bashrc

PATH=$PATH:/usr/lib/nvidia-cuda-toolkit/bin.
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-cuda-toolkit/lib:/lib
export PATH
export LD_LIBRARY_PATH

*Pyrit_Cuda Prep and Install

cd /root/Pyrit/modules/cpyrit_cuda/

gedit setup.py

Edit the setup.py, line 35,edit it from*

for path in ('/usr/local/cuda', '/opt/cuda'):

*to:

for path in ('/usr/local/cuda','/usr/lib/nvidia-cuda-toolkit','/opt/cuda'):

line 88,edit it from**

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

*then

cd /root/Pyrit

*and install

python setup.py clean build install

*last thing

gedit /root/.pyrit/config

*change from:

use_CUDA = false

*to

use_CUDA = true

*now check your GPU

pyrit list_cores

ENJOY !!!

*Note: GPU works best with 1 CPU core
gedit /root/.pyrit/config
*set:
limit_ncpus = 1

My score:

root@kali:/# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (120907.2 PMKs/s)... \

Computed 120907.24 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 1112.1 PMKs/s (RTT 3.1)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1060 3GB'': 130434.6 PMKs/s (RTT 1.0)

**Comment by kudzie567** [comment]
Thanks for the above instructions, now i can use my gpu successfully

**Comment by PastiiJ** [comment]
root@KaliDesktop:~# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (235388.1 PMKs/s)... \ 

Computed 235388.14 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 1401.0 PMKs/s (RTT 3.0)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1080 Ti'': 256912.6 PMKs/s (RTT 0.5)


Just OC first core of my 6700k to 4,8Ghz ≃ 12000PMKs/s more than stock (244530.3 PMKs/s) with limit_ncpus = 1

CPU bottleneck GPU,
so i try to disable all cores:
edit /root/.pyrit/config
limit_ncpus = -4

But it crash after 30sec..

Can we run this only with GPU?

Thx

**Comment by PastiiJ** [comment]
root@KaliDesktop:~# pyrit benchmark
Pyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Running benchmark (235388.1 PMKs/s)... \ 

Computed 235388.14 PMKs/s total.
#1: 'CPU-Core (SSE2/AES)': 1401.0 PMKs/s (RTT 3.0)
CUDA:
#1: 'CUDA-Device #1 'GeForce GTX 1080 Ti'': 256912.6 PMKs/s (RTT 0.5)


Just OC first core of my 6700k to 4,8Ghz ≃ 12000PMKs/s more than stock (244530.3 PMKs/s) with limit_ncpus = 1

CPU bottleneck GPU,
so i try to disable all cores:
edit /root/.pyrit/config
limit_ncpus = -4

But it crash after 30sec..

Can we run this only with GPU?

Thx

**Comment by h3xcmd** [comment]
I have to remember

> cd /root/Pyrit/modules/cpyrit_cuda/
> gedit setup.py

`nvcc_cmd = NVCC + bit_flag + ' -ccbin **clang-3.8** -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'`

**Comment by c3ph3u5qwerty** [comment]
@Hackitfree can i help me please, i have a laptop hp omen with intel and nvidia 1050 and i want install nvidia driver with cuda for use pyrit. is the same method that in your answer?

**Comment by Hackitfree** [comment]
@ c3ph3u5qwerty - Well i guess its same with your laptop-One thing..If your laptop uses the integrated graphics and switch between modes then you should consider https://github.com/h3xcmd this can help..
I didnt try installing the newest version of KaliLinux yet-i hope something is improved with their installed already version of Pyrit..However try  my guide and post what you have done..I will try resolving any issue you might have..

**Comment by c3ph3u5qwerty** [comment]
@Hackitfree very very thanks, this method works :) but i have a question with pyrit (i use parrot OS on other laptop, and installed pyrit compatible with opencl). and works but when reboot my laptop pyrit doesn't recognize my gpu.  you know what's going on?

**Comment by Hackitfree** [comment]
@ pwnhun73r  Hmmm.. So you made pyrit work-but when you restarted laptop-it wouldnt recognise GPU?..It might be some problem with switchable graphics in your laptop..Try to solve with some trick with "Optimus":
https://forums.kali.org/showthread.php?35748-TUTORIAL-Installing-official-NVIDIA-driver-in-Optimus-laptop&highlight=nvidia
http://www.hackdig.com/?07/hack-4577.htm
https://svn.boost.org/trac10/attachment/ticket/11852/float128GccNvcc.patch

I hope  it will help-i never worked with Pyrit on laptop swichable graphics so i dont know where is the problem...

**Comment by kur4kwdz** [comment]
Could u help me with this:

root@kali:/opt/Pyrit/modules/cpyrit_cuda# python setup.py clean build install 
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
clang-3.8: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1

**Comment by Hackitfree** [comment]
Did you follow all instructions?
If yes then try to compile it without any changes in lines of setyp.py..
The newest version of Kali dont need this changes!

**Comment by kur4kwdz** [comment]
without any changes compiler returns:
`root@kali:/opt/Pyrit/modules/cpyrit_cuda# python setup.py clean build install
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 8.0, V8.0.61...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc fatal   : The version ('40001') of the host compiler ('clang') is not supported
Traceback (most recent call last):
  File "setup.py", line 166, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 91, in run
    subprocess.check_call(nvcc_cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/cuda/bin/nvcc -m64 -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu' returned non-zero exit status 1
`

**Comment by Hackitfree** [comment]
So you followed my tutorial ?? Try compiling like this with clang 3.8:

*Pyrit_Cuda Prep and Install

cd /root/Pyrit/modules/cpyrit_cuda/

gedit setup.py

Edit the setup.py, line 35,edit it from*

for path in ('/usr/local/cuda', '/opt/cuda'):

*to:

for path in ('/usr/local/cuda','/usr/lib/nvidia-cuda-toolkit','/opt/cuda'):

line 88,edit it from**

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

nvcc_cmd = NVCC + bit_flag + ' -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'

*then

cd /root/Pyrit

*and install

python setup.py clean build install

*last thing

gedit /root/.pyrit/config

*change from:

use_CUDA = false

*to

use_CUDA = true

*now check your GPU

pyrit list_cores

You must have some kind of "clang" installed..
Did you install Nvidia cuda?
Tell me what result will get  now!

**Comment by vido89** [comment]
@Hackitfree Tnx for instructions I followed it but Im getting an error

```
  $ python setup.py clean build install
running clean
Removing temporary files and pre-built GPU-kernels...
running build
running build_ext
Compiling CUDA module using nvcc 10.0, V10.0.130...
Executing '/usr/local/cuda/bin/nvcc -m64 -ccbin clang-3.8 -Xcompiler "-fPIC" --ptx ./_cpyrit_cudakernel.cu'
Building modules...
running install
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/cpyrit_cuda-0.5.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/cpyrit_cuda-0.5.0.egg-info
slobodan@G31M-ES2L:~/Pyrit/modules/cpyrit_cuda$ pyrit list_coresPyrit 0.5.1 (C) 2008-2011 Lukas Lueg - 2015 John Mora
https://github.com/JPaulMora/Pyrit
This code is distributed under the GNU General Public License v3+

Traceback (most recent call last):
  File "/usr/local/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 117, in initFromArgv
    func(self, **options)
  File "/usr/local/lib/python2.7/dist-packages/pyrit_cli.py", line 294, in list_cores
    with cpyrit.cpyrit.CPyrit() as cp:
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 442, in __init__
    self.CUDAs.append(CUDACore(queue=self, dev_idx=dev_idx))
  File "/usr/local/lib/python2.7/dist-packages/cpyrit/cpyrit.py", line 243, in __init__
    _cpyrit_cuda.CUDADevice.__init__(self, dev_idx)
SystemError: Unknown CUresult.
```
