### ISSUE TITLE
Errors when building setup.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [JPaulMora/Pyrit#410]
```
What steps will reproduce the problem?
1. When I run python setup.py build in /root/cpyrit-opencl-0.3.0

What is the expected output? What do you see instead?
My expected output... not sure.

My output:
The headers required to build the OpenCL-kernel were not found. Trying to 
continue anyway...
svn: '.' is not a working copy
running build
running build_ext
Building modules...
building 'cpyrit._cpyrit_opencl' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall 
-Wstrict-prototypes -fPIC -I/usr/include/python2.6 -c _cpyrit_opencl.c -o 
build/temp.linux-x86_64-2.6/_cpyrit_opencl.o -DVERSION="0.3.0"
_cpyrit_opencl.c:23:19: error: CL/cl.h: No such file or directory
_cpyrit_opencl.c:46: error: expected specifier-qualifier-list before 
‘cl_device_id’
_cpyrit_opencl.c:57: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or 
‘__attribute__’ before ‘*’ token
_cpyrit_opencl.c:58: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or 
‘__attribute__’ before ‘num_platforms’
_cpyrit_opencl.c:63: error: expected ‘)’ before ‘error’
_cpyrit_opencl.c: In function ‘oclplatf_init’:
_cpyrit_opencl.c:122: error: ‘cl_uint’ undeclared (first use in this 
function)
_cpyrit_opencl.c:122: error: (Each undeclared identifier is reported only once
_cpyrit_opencl.c:122: error: for each function it appears in.)
_cpyrit_opencl.c:122: error: expected ‘;’ before ‘num_devices’
_cpyrit_opencl.c:123: error: ‘cl_int’ undeclared (first use in this 
function)
_cpyrit_opencl.c:123: error: expected ‘;’ before ‘err’
_cpyrit_opencl.c:130: error: ‘num_platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:140: error: ‘err’ undeclared (first use in this function)
_cpyrit_opencl.c:140: warning: implicit declaration of function 
‘clGetDeviceIDs’
_cpyrit_opencl.c:140: error: ‘platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:140: error: ‘CL_DEVICE_TYPE_ALL’ undeclared (first use in 
this function)
_cpyrit_opencl.c:140: error: ‘num_devices’ undeclared (first use in this 
function)
_cpyrit_opencl.c:141: error: ‘CL_SUCCESS’ undeclared (first use in this 
function)
_cpyrit_opencl.c:143: warning: implicit declaration of function 
‘getCLresultMsg’
_cpyrit_opencl.c:154: warning: implicit declaration of function 
‘clGetPlatformInfo’
_cpyrit_opencl.c:154: error: ‘CL_PLATFORM_NAME’ undeclared (first use in 
this function)
_cpyrit_opencl.c:167: error: ‘CL_PLATFORM_VENDOR’ undeclared (first use in 
this function)
_cpyrit_opencl.c: In function ‘ocldevice_init’:
_cpyrit_opencl.c:196: error: ‘cl_uint’ undeclared (first use in this 
function)
_cpyrit_opencl.c:196: error: expected ‘;’ before ‘num_entries’
_cpyrit_opencl.c:197: error: ‘cl_device_id’ undeclared (first use in this 
function)
_cpyrit_opencl.c:197: error: ‘devices’ undeclared (first use in this 
function)
_cpyrit_opencl.c:198: error: ‘cl_device_type’ undeclared (first use in this 
function)
_cpyrit_opencl.c:198: error: expected ‘;’ before ‘device_type’
_cpyrit_opencl.c:202: error: ‘cl_int’ undeclared (first use in this 
function)
_cpyrit_opencl.c:202: error: expected ‘;’ before ‘err’
_cpyrit_opencl.c:207: error: ‘num_platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:213: error: ‘err’ undeclared (first use in this function)
_cpyrit_opencl.c:213: error: ‘platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:213: error: ‘CL_DEVICE_TYPE_ALL’ undeclared (first use in 
this function)
_cpyrit_opencl.c:213: error: ‘num_entries’ undeclared (first use in this 
function)
_cpyrit_opencl.c:214: error: ‘CL_SUCCESS’ undeclared (first use in this 
function)
_cpyrit_opencl.c:225: error: expected expression before ‘)’ token
_cpyrit_opencl.c:238: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:241: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:241: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:241: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:242: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:243: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:244: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:245: error: ‘OpenCLDevice’ has no member named 
‘dev_queue’
_cpyrit_opencl.c:247: warning: implicit declaration of function 
‘clGetDeviceInfo’
_cpyrit_opencl.c:247: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:247: error: ‘CL_DEVICE_NAME’ undeclared (first use in this 
function)
_cpyrit_opencl.c:253: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:254: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:260: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:260: error: ‘CL_DEVICE_TYPE’ undeclared (first use in this 
function)
_cpyrit_opencl.c:260: error: ‘device_type’ undeclared (first use in this 
function)
_cpyrit_opencl.c:266: error: ‘CL_DEVICE_TYPE_CPU’ undeclared (first use in 
this function)
_cpyrit_opencl.c:268: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:269: error: ‘CL_DEVICE_TYPE_GPU’ undeclared (first use in 
this function)
_cpyrit_opencl.c:271: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:272: error: ‘CL_DEVICE_TYPE_ACCELERATOR’ undeclared (first 
use in this function)
_cpyrit_opencl.c:274: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:277: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:279: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:285: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:285: error: ‘CL_DEVICE_MAX_WORK_GROUP_SIZE’ undeclared 
(first use in this function)
_cpyrit_opencl.c:285: error: ‘OpenCLDevice’ has no member named 
‘dev_workgroupsize’
_cpyrit_opencl.c:285: error: ‘OpenCLDevice’ has no member named 
‘dev_workgroupsize’
_cpyrit_opencl.c:292: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:292: error: ‘CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS’ 
undeclared (first use in this function)
_cpyrit_opencl.c:305: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:305: error: ‘CL_DEVICE_MAX_WORK_ITEM_SIZES’ undeclared 
(first use in this function)
_cpyrit_opencl.c:312: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:313: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:320: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c: In function ‘ocldevice_compile’:
_cpyrit_opencl.c:330: error: ‘cl_int’ undeclared (first use in this 
function)
_cpyrit_opencl.c:330: error: expected ‘;’ before ‘err’
_cpyrit_opencl.c:332: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:334: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:334: warning: implicit declaration of function 
‘clCreateContext’
_cpyrit_opencl.c:334: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:334: error: ‘err’ undeclared (first use in this function)
_cpyrit_opencl.c:335: error: ‘CL_SUCCESS’ undeclared (first use in this 
function)
_cpyrit_opencl.c:342: error: ‘OpenCLDevice’ has no member named 
‘dev_queue’
_cpyrit_opencl.c:344: error: ‘OpenCLDevice’ has no member named 
‘dev_queue’
_cpyrit_opencl.c:344: warning: implicit declaration of function 
‘clCreateCommandQueue’
_cpyrit_opencl.c:344: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:344: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:352: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:354: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:354: warning: implicit declaration of function 
‘clCreateProgramWithSource’
_cpyrit_opencl.c:354: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:362: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:364: warning: implicit declaration of function 
‘clBuildProgram’
_cpyrit_opencl.c:364: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:367: warning: implicit declaration of function 
‘clGetProgramBuildInfo’
_cpyrit_opencl.c:367: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:367: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:367: error: ‘CL_PROGRAM_BUILD_LOG’ undeclared (first use 
in this function)
_cpyrit_opencl.c:372: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:372: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:372: error: ‘CL_PROGRAM_BUILD_STATUS’ undeclared (first 
use in this function)
_cpyrit_opencl.c:372: error: ‘status’ undeclared (first use in this 
function)
_cpyrit_opencl.c:373: error: ‘CL_BUILD_SUCCESS’ undeclared (first use in 
this function)
_cpyrit_opencl.c:375: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:375: error: ‘OpenCLDevice’ has no member named ‘device’
_cpyrit_opencl.c:380: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:380: warning: implicit declaration of function 
‘clCreateKernel’
_cpyrit_opencl.c:380: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c: In function ‘ocldevice_dealloc’:
_cpyrit_opencl.c:395: error: ‘OpenCLDevice’ has no member named 
‘dev_queue’
_cpyrit_opencl.c:396: warning: implicit declaration of function 
‘clReleaseCommandQueue’
_cpyrit_opencl.c:396: error: ‘OpenCLDevice’ has no member named 
‘dev_queue’
_cpyrit_opencl.c:397: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:398: warning: implicit declaration of function 
‘clReleaseKernel’
_cpyrit_opencl.c:398: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:399: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:400: warning: implicit declaration of function 
‘clReleaseProgram’
_cpyrit_opencl.c:400: error: ‘OpenCLDevice’ has no member named 
‘dev_prog’
_cpyrit_opencl.c:401: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:402: warning: implicit declaration of function 
‘clReleaseContext’
_cpyrit_opencl.c:402: error: ‘OpenCLDevice’ has no member named 
‘dev_ctx’
_cpyrit_opencl.c:403: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:403: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:403: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:403: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:404: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:404: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:404: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:404: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:405: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:405: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:405: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c:405: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c: At top level:
_cpyrit_opencl.c:410: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or 
‘__attribute__’ before ‘calc_pmklist’
_cpyrit_opencl.c: In function ‘cpyrit_solve’:
_cpyrit_opencl.c:494: error: ‘OpenCLDevice’ has no member named 
‘dev_kernel’
_cpyrit_opencl.c:589: warning: implicit declaration of function 
‘calc_pmklist’
_cpyrit_opencl.c:593: error: ‘CL_SUCCESS’ undeclared (first use in this 
function)
_cpyrit_opencl.c:596: warning: format ‘%s’ expects type ‘char *’, but 
argument 3 has type ‘int’
_cpyrit_opencl.c: At top level:
_cpyrit_opencl.c:670: error: ‘OpenCLDevice’ has no member named 
‘dev_name’
_cpyrit_opencl.c:671: error: ‘OpenCLDevice’ has no member named 
‘dev_type’
_cpyrit_opencl.c:672: error: ‘OpenCLDevice’ has no member named 
‘dev_maxworksize’
_cpyrit_opencl.c: In function ‘init_cpyrit_opencl’:
_cpyrit_opencl.c:737: error: ‘cl_int’ undeclared (first use in this 
function)
_cpyrit_opencl.c:737: warning: statement with no effect
_cpyrit_opencl.c:737: error: expected ‘;’ before ‘err’
_cpyrit_opencl.c:739: error: ‘err’ undeclared (first use in this function)
_cpyrit_opencl.c:739: warning: implicit declaration of function 
‘clGetPlatformIDs’
_cpyrit_opencl.c:739: error: ‘num_platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:739: warning: statement with no effect
_cpyrit_opencl.c:740: error: ‘CL_SUCCESS’ undeclared (first use in this 
function)
_cpyrit_opencl.c:742: warning: format ‘%s’ expects type ‘char *’, but 
argument 3 has type ‘int’
_cpyrit_opencl.c:746: error: ‘platforms’ undeclared (first use in this 
function)
_cpyrit_opencl.c:746: error: ‘cl_platform_id’ undeclared (first use in this 
function)
_cpyrit_opencl.c:746: error: invalid operands to binary / (have ‘long int’ 
and ‘struct PyMemberDef *’)
_cpyrit_opencl.c:746: warning: comparison between pointer and integer
_cpyrit_opencl.c:746: error: expected expression before ‘)’ token
_cpyrit_opencl.c:746: error: invalid operands to binary * (have ‘struct 
PyMemberDef *’ and ‘struct PyMemberDef *’)
_cpyrit_opencl.c:746: warning: statement with no effect
_cpyrit_opencl.c:753: warning: statement with no effect
_cpyrit_opencl.c:756: warning: format ‘%s’ expects type ‘char *’, but 
argument 3 has type ‘int’
error: command 'gcc' failed with exit status 1


What version of the product are you using? On what operating system?
pyrit 0.3.0
Backtrack 5r3

Please provide any additional information below.
Which header(s) am I missing?
```

Original issue reported on code.google.com by `Jcbw...@gmail.com` on 4 Dec 2012 at 1:56
